### ISSUE TITLE
Week-02 : Experiment Missing

### ISSUE THREAD

**Issue by rishi11** [MichaelBarb/CS5610-barbm#1]
One experiment is missing in week02. I can see only 4 experiments.

**Comment by MichaelBarb** [comment]
The last experiment was really 5 experiments noted in the experiment page.  Setting up a master page in aspx required working with a lot of techniques.  It was probably more than 5.  In total for that week I am sure I had at least 9 experiments.

I studied your website for the project and saw that you did this often.  I was mostly just following your format.
