### ISSUE TITLE
Project and Project Related Experiments 

### ISSUE THREAD

**Issue by rishi11** [MichaelBarb/CS5610-barbm#10]
Please perform experiments based on your project.

**Comment by MichaelBarb** [comment]
Please see blog entry for the week.  My project is focusing on animation.   The blog entry will explain more how the experiments tie into the project.

I already talked to the professor about it an got approval. 

Not also that some weeks I did more than 5 experiments.  I already had my 45 total.  I just added 4 more.

**Comment by MichaelBarb** [comment]
I added 2 more for last week.  I did the work last week on all 6 but spent a lot of time on them.  l finally got them all published.  Publishing took me about 9 hours total.  The code snippets take a good part of that.

In total that now gives me 51 experiments.

**Comment by rishi11** [comment]
I am really Sorry. This issue will not be counted as issues raised while generating the final report.

**Comment by MichaelBarb** [comment]
What is the issue pending?  I did experiments base on my project.  I have the required 50 experiments total.

**Comment by rishi11** [comment]
Yes thats what I am saying. I am really sorry for raising this issue on your Git. I will not count this issue in your final report. Hence in actual there are 10 issues raised on your Git but I will count only 9 excluding this.
