### ISSUE TITLE
Week04 : Experiment Missing

### ISSUE THREAD

**Issue by rishi11** [MichaelBarb/CS5610-barbm#2]
One experiment is missing in week 04. There are only 4 experiments.

**Comment by MichaelBarb** [comment]
The 4th experiment write up was 2 different experiments in the same write up.  I noted this in the experiment page title.  I guess I should have made the notation bolder.

**Comment by MichaelBarb** [comment]
I should have noted in the comment that one experiment was in Internet Explorer and one was in Chrome.
