### ISSUE TITLE
Code Snippet Missing.

### ISSUE THREAD

**Issue by rishi11** [MichaelBarb/CS5610-barbm#4]
In week03 and week04, Code snippet in experiment documentation is missing.

**Comment by MichaelBarb** [comment]
In week 4 the first 3 experiments had a code snippet.  In the last 2 (same write up) a code snippet was not applicable.  This dealt with page buffering in the browser.  The solution were browser settings.

**Comment by MichaelBarb** [comment]
In week03 I added some code snippets to the last 4.  For the first experiment the entire source would need to be included which then is not a snippet.  It can be accessed threw the source code link.
