### ISSUE TITLE
Week 5 : Experiments Missing

### ISSUE THREAD

**Issue by rishi11** [MichaelBarb/CS5610-barbm#5]
You submitted 3 files which will be considered as 3 experiments, However you have created multiple experiments in one file but those will be counted as one. 

Please create all experiments in separate file.

**Comment by MichaelBarb** [comment]
I spoke with the professor last Wednesday.  He said that the way that I formatted it was OK to have more than one experiment in a file.  His only request was that I add links to the subtitles in the header to the section of the page for that experiment.  For Week 5 I have 8 experiments.
