### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by rishi11** [MichaelBarb/CS5610-barbm#6]
I cannot find your experiment's HTML pages in your website file structure. Your experiments should be contained in experiment folder with sub folders in it.

**Comment by MichaelBarb** [comment]
Everything is in myExperiments folder.  Each week in a separate sub-folder.

**Comment by rishi11** [comment]
myExperiments or myTests ?

**Comment by MichaelBarb** [comment]
You are correct, myTests.  A habit from many years is the prefix "my".  In the case of this class it is everything that I am writing.  The one exception is "blog_entries" which I really do not have a choice of the folder name.  There are a few things that I downloaded that are used as is.  These are "Contents" and "Scripts".  These names beginning with a capital letter was a default in on one of the installs.  The capital letter does kind of flag that they were not part of the original Essentials.
