### ISSUE TITLE
No Experiments This Week.

### ISSUE THREAD

**Issue by rishi11** [MichaelBarb/CS5610-barbm#8]
Every week you are supposed to perform 5 experiments but I cannot find any this week. Please perform at-least five experiments for this week.

**Comment by MichaelBarb** [comment]
I have had a cold and have basically lost several days in bed.  I am still not totally recovered.  I will make up the lost week on the spring break we have coming up shortly.

**Comment by rishi11** [comment]
Please close the issue when you fix it. Not before that.

**Comment by MichaelBarb** [comment]
All caught up.
