### ISSUE TITLE
Broken Link to Image

### ISSUE THREAD

**Issue by rishi11** [MichaelBarb/CS5610-barbm#9]
Experiment 3:

http://net4.ccs.neu.edu/home/barbm/myTests/Week08/Home.html

Please fix

**Comment by MichaelBarb** [comment]
The link is to a .svg file.  I do not understand why our server will not deliver it.  It works locally.  It is on the server in the correct place.  I am researching more and maybe placing a question on Piazza.

**Comment by MichaelBarb** [comment]
It seems our file serve will not serve svg image files.  Note my question in Piazza.  I hard coded the diagram in the page.  When doing this the diagram is no longer responsive.  If I am able to get our server to updated I will revert back to the svg image.

**Comment by MichaelBarb** [comment]
They updated the server so I was able to go back to the svg file image.  I am really, really amazed how quickly that happened.
